### ISSUE TITLE
Dokümanlarda eksiklik

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2021-2022-Unmanned-Aerial-Vehicle-UAV-#1]
SRS dokümanı eksik. Wiki sayfası olarak oluşturup wiki home sayfasına ve pages panel'ine linkini ekleyin.
Ayrıca pages panel'iniz kapalı geliyor. Altındaki tablo ise word halini indiriyor. Burası yanıltıcı olmuş. Bu küçük tabloyu kaldırıp home sayfası içine alın gerekirse.
Pages panelinin sayfaya girdiğinde açık olarak gelmesini sağlayın lütfen.

**Comment by fstasel** [comment]
SRS, SDD dokümanları eklenmeli.

**Comment by fstasel** [comment]
Proje websitesi de eksik görünüyor şu an.

**Comment by CanAtesApps** [comment]
Hocam proje web sitesini ekledim, aşağıya footer şeklinde koydum. Home sayfasında en başada link olarak ekledim hangi şekilde kalmasını uygun görürseniz öbür tarafı düzenlerim. 

İlginiz ve anlayışınız için teşekkür ederim.
